title: SOC Workstation Documentation
description: All the necessary infos on how to deploy and use the SOC Workstation
theme: just-the-docs

url: https://stretfordStart.github.io/soc_workstation_doc

aux_links:
  SOC Workstation: https://github.com/stretfordStart/soc_workstation
aux_links_new_tab: true

color_scheme: nil

# For copy button on code
enable_copy_code_button: true

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

exclude:
  - README.md
  - example/README.md
  - Gemfile
  - Gemfile.lock
  - assets/css/just-the-docs-switchable-src.css
  - _sass # I have used pure CSS now
  - serve
